name: Auto Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '31 0 8 4 *'
    - cron: '25 3 8 4 *'
    - cron: '24 4 8 4 *'
    - cron: '16 6 8 4 *'
    - cron: '55 8 8 4 *'
    - cron: '54 10 8 4 *'
    - cron: '54 13 8 4 *'
    - cron: '56 14 8 4 *'
    - cron: '38 16 8 4 *'
    - cron: '37 18 8 4 *'
    - cron: '23 21 8 4 *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Create Single Change
        run: |
          node ./auto_commit_script.js
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Auto commit [$(date -u)]"
          git push