name: Auto Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '6 1 4 4 *'
    - cron: '18 2 4 4 *'
    - cron: '9 3 4 4 *'
    - cron: '28 3 4 4 *'
    - cron: '5 4 4 4 *'
    - cron: '52 6 4 4 *'
    - cron: '7 6 4 4 *'
    - cron: '7 7 4 4 *'
    - cron: '48 9 4 4 *'
    - cron: '56 9 4 4 *'
    - cron: '26 10 4 4 *'
    - cron: '44 12 4 4 *'
    - cron: '34 12 4 4 *'
    - cron: '29 14 4 4 *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Create Single Change
        run: |
          node ./auto_commit_script.js
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Auto commit [$(date -u)]"
          git push